name: Terraform Destroy AWS Infrastructure

on:
  workflow_dispatch:  # Manual trigger from GitHub Actions UI

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.1  # Specify your required Terraform version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change as per your AWS region

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform  # Change path if your TF files are elsewhere

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: C:\Users\LENOVO\CRATE-TERRAFORM-SETUP\CRATE-TERRAFORM-SETUP\.terraform
